### ISSUE TITLE
TypeError: $(...).flexVerticalCenter is not a function

### ISSUE THREAD

**Issue by mrcampbell06** [PaulSpr/jQuery-Flex-Vertical-Center#16]
I get the above error in my FF console. But not sure why. The script tag is loaded after jquery is loaded. And my site.js file is loaded in the at the end of my body tag. Can someone assist with correcting this error?

mysite: http://truelight-estl.com/

**Comment by PaulSpr** [comment]
Is the problem solved? I checked the website in Firefox and Safari, but didn't get the error you described.

Stuff that might make that error happen is:
- Source order issue. You need to call the flexVerticalCenter after both jQuery and the plugin are loaded.
- document.load issue. If you wrap the call to flexVerticalCenter in a `$(document).load(function(){ ...call here... })` than you can be sure that all the proper plugins are loaded when the plugin gets called. But still, call that after you've loaded all the plugins.

**Comment by mrcampbell06** [comment]
Yes I fixed the error when fixing some issues with loading jquery for another script that I was using.
